# Generated by Django 5.0 on 2024-07-17 07:10

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('obejects', django.db.models.manager.Manager()),
            ],
        ),
    ]
